### ISSUE TITLE
Repo updates

### ISSUE THREAD

**Issue by kalemas** [greg-hellings/sword#4]
I had just noticed that this repo is not up to date with https://crosswire.org/svn/sword, CMakeLists.txt states that this is 1.7.3, but 1.7.4 is latest.

So, plan you to maintain this repository or i have to look for another base for making a patches for upstream?

**Comment by greg-hellings** [comment]
Sword does not accept git pull requests from any source. I maintain this as my own method of syncing work between various machines, so it updates manually at my leisure. If you want to submit patches, you'll need to send them via email to the sword-devel list.

**Comment by kalemas** [comment]
I got. It is your personal repo and may contain work absent in official sword svn.

I ll make my own mirror, because I need svn head to prepare a patches, not to pull request.
